gender_list = ["Male", "Female"]

race_dict = {
  "Human" : ["Meadow Folk", "Savannah Folk", "Ocean Folk"],
  "Elf" : ["Wood Elf", "Pale Elf"],
  "Dwarf" : ["Mountain Dwarf", "Boreal Dwarf"],
  "Orlan" : ["Hearth Orlan", "Wild Orlan"],
  "Aumaua" : ["Coastal Aumaua", "Island Aumaua"],
  "Godlike" : ["Fire Godlike", "Death Godlike", "Moon Godlike", "Nature Godlike"]
}
race_link_dict = {
  "Aumaua" : r"https://pillarsofeternity2.wiki.fextralife.com/aumaua",
  "Dwarf" : r"https://pillarsofeternity2.wiki.fextralife.com/Dwarf",
  "Elf" : r"https://pillarsofeternity2.wiki.fextralife.com/Elf",
  "Human" : r"https://pillarsofeternity2.wiki.fextralife.com/Human",
  "Godlike" : r"https://pillarsofeternity2.wiki.fextralife.com/Godlike",
  "Orlan" : r"https://pillarsofeternity2.wiki.fextralife.com/Orlan",
}


class_dict = {
  "Barbarian" : ["Beserker", "Corpse-Eater", "Mage Slayer"],
  "Chanter" : ["Beckoner", "Skald", "Trobadour"],
  "Cipher" : ["Ascendant", "Beguiler", "Soul Blade"],
  "Druid" : ["Animist", "Fury", "Lifegiver", "Shifter"],
  "Fighter" : ["Blackjack", "Devoted", "Unbroken"],
  "Monk" : ["Helwalker", "Nalpazca", "Shattered Pillar"],
  "Paladin" : ["Bleakwalkers", "Darcozzi Paladins", "Goldpact Knights", "Kind Wayfarers", "The Shieldbearers of St. Elcga"],
  "Priest" : ["Priest of Berath", "Priest of Eothas", "Priest of Magran", "Priest of Skaen", "Priest of Wael"],
  "Ranger" : ["Sharpshooter", "Ghost Heart", "Stalker"],
  "Rogue" : ["Assassin", "Streetfighter", "Trickster"],
  "Wizard" : ["Conjurer", "Enchanter", "Evoker", "Illusionist", "Transmuter", "(no subclass)"]
}

class_link_dict = {
 "Barbarian" : "https://pillarsofeternity2.wiki.fextralife.com/Barbarian",
 "Chanter" : "https://pillarsofeternity2.wiki.fextralife.com/Chanter",
 "Cipher" : "https://pillarsofeternity2.wiki.fextralife.com/Cipher",
 "Druid" : "https://pillarsofeternity2.wiki.fextralife.com/Druid",
 "Fighter" : "https://pillarsofeternity2.wiki.fextralife.com/Fighter",
 "Monk" : "https://pillarsofeternity2.wiki.fextralife.com/Monk",
 "Paladin" : "https://pillarsofeternity2.wiki.fextralife.com/Paladin",
 "Priest" : "https://pillarsofeternity2.wiki.fextralife.com/Priest",
 "Ranger" : "https://pillarsofeternity2.wiki.fextralife.com/Ranger",
 "Rogue" : "https://pillarsofeternity2.wiki.fextralife.com/Rogue",
 "Wizard" : "https://pillarsofeternity2.wiki.fextralife.com/Wizard",
 "Howler" : "https://pillarsofeternity2.wiki.fextralife.com/Howler",
 "Witch" : "https://pillarsofeternity2.wiki.fextralife.com/Witch",
 "Tempest" : "https://pillarsofeternity2.wiki.fextralife.com/Tempest",
 "Brute" : "https://pillarsofeternity2.wiki.fextralife.com/Brute",
 "Ravager" : "https://pillarsofeternity2.wiki.fextralife.com/Ravager",
 "Fanatic" : "https://pillarsofeternity2.wiki.fextralife.com/Fanatic",
 "Shaman" : "https://pillarsofeternity2.wiki.fextralife.com/Shaman",
 "Savage" : "https://pillarsofeternity2.wiki.fextralife.com/Savage",
 "Marauder" : "https://pillarsofeternity2.wiki.fextralife.com/Marauder",
 "Warlock" : "https://pillarsofeternity2.wiki.fextralife.com/Warlock",
 "Spiritualist" : "https://pillarsofeternity2.wiki.fextralife.com/Spiritualist",
 "Theurge" : "https://pillarsofeternity2.wiki.fextralife.com/Theurge",
 "War Caller" : "https://pillarsofeternity2.wiki.fextralife.com/War+Caller",
 "Cantor" : "https://pillarsofeternity2.wiki.fextralife.com/Cantor",
 "Herald" : "https://pillarsofeternity2.wiki.fextralife.com/Herald",
 "Celebrant" : "https://pillarsofeternity2.wiki.fextralife.com/Celebrant",
 "Wildrhymer" : "https://pillarsofeternity2.wiki.fextralife.com/Wildrhymer",
 "Harbinger" : "https://pillarsofeternity2.wiki.fextralife.com/Harbinger",
 "Loremaster" : "https://pillarsofeternity2.wiki.fextralife.com/Loremaster",
 "Oracle" : "https://pillarsofeternity2.wiki.fextralife.com/Oracle",
 "Psyblade" : "https://pillarsofeternity2.wiki.fextralife.com/Psyblade",
 "Transcendant" : "https://pillarsofeternity2.wiki.fextralife.com/Transcendent",
 "Inquisitor" : "https://pillarsofeternity2.wiki.fextralife.com/Inquisitor",
 "Mystic" : "https://pillarsofeternity2.wiki.fextralife.com/Mystic",
 "Seer" : "https://pillarsofeternity2.wiki.fextralife.com/Seer",
 "Mindstalker" : "https://pillarsofeternity2.wiki.fextralife.com/Mindstalker",
 "Hierophant" : "https://pillarsofeternity2.wiki.fextralife.com/Hierophant",
 "Warden" : "https://pillarsofeternity2.wiki.fextralife.com/Warden",
 "Ascetic" : "https://pillarsofeternity2.wiki.fextralife.com/Ascetic",
 "Liberator" : "https://pillarsofeternity2.wiki.fextralife.com/Liberator",
 "Universalist" : "https://pillarsofeternity2.wiki.fextralife.com/Universalist",
 "Beastmaster" : "https://pillarsofeternity2.wiki.fextralife.com/Beastmaster",
 "Pathfinder" : "https://pillarsofeternity2.wiki.fextralife.com/Pathfinder",
 "Sorcerer" : "https://pillarsofeternity2.wiki.fextralife.com/Sorceror",
 "Brawler" : "https://pillarsofeternity2.wiki.fextralife.com/Brawler",
 "Crusader" : "https://pillarsofeternity2.wiki.fextralife.com/Crusader",
 "Cleric" : "https://pillarsofeternity2.wiki.fextralife.com/Cleric",
 "Hunter" : "https://pillarsofeternity2.wiki.fextralife.com/Hunter",
 "Swashbuckler" : "https://pillarsofeternity2.wiki.fextralife.com/Swashbuckler",
 "Battlemage" : "https://pillarsofeternity2.wiki.fextralife.com/Battlemage",
 "Votary" : "https://pillarsofeternity2.wiki.fextralife.com/Votary",
 "Contemplative" : "https://pillarsofeternity2.wiki.fextralife.com/Contemplative",
 "Wanderer" : "https://pillarsofeternity2.wiki.fextralife.com/Wanderer",
 "Shadowdancer" : "https://pillarsofeternity2.wiki.fextralife.com/Shadowdancer",
 "Sage" : "https://pillarsofeternity2.wiki.fextralife.com/Sage",
 "Templar" : "https://pillarsofeternity2.wiki.fextralife.com/Templar",
 "Shephard" : "https://pillarsofeternity2.wiki.fextralife.com/Shepherd",
 "Holy Slayer" : "https://pillarsofeternity2.wiki.fextralife.com/Holy+Slayer",
 "Arcane Knight" : "https://pillarsofeternity2.wiki.fextralife.com/Arcane+Knight",
 "Itinerant" : "https://pillarsofeternity2.wiki.fextralife.com/Itinerant",
 "Zealot" : "https://pillarsofeternity2.wiki.fextralife.com/Zealot",
 "Thaumaturge" : "https://pillarsofeternity2.wiki.fextralife.com/Thaumaturge",
 "Scout" : "https://pillarsofeternity2.wiki.fextralife.com/Scout",
 "Geomancer" : "https://pillarsofeternity2.wiki.fextralife.com/Geomancer",
 "Spellblade" : "https://pillarsofeternity2.wiki.fextralife.com/Spellblade",
}

multiclass_dict = {
  "Howler" : ["Barbarian", "Chanter"],
  "Witch" : ["Barbarian", "Cipher"],
  "Tempest" : ["Barbarian", "Druid"],
  "Brute" : ["Barbarian", "Fighter"],
  "Ravager" : ["Barbarian", "Monk"],
  "Fanatic" : ["Barbarian", "Paladin"],
  "Shaman" : ["Barbarian", "Priest"],
  "Savage" : ["Barbarian", "Ranger"],
  "Marauder" : ["Barbarian", "Rogue"],
  "Warlock" : ["Barbarian", "Wizard"],
  "Spiritualist" : ["Chanter", "Cipher"],
  "Theurge" : ["Chanter", "Druid"],
  "War Caller" : ["Chanter", "Fighter"],
  "Cantor" : ["Chanter", "Monk"],
  "Herald" : ["Chanter", "Paladin"],
  "Celebrant" : ["Chanter", "Priest"],
  "Wildrhymer" : ["Chanter", "Ranger"],
  "Harbinger" : ["Chanter", "Rogue"],
  "Loremaster" : ["Chanter", "Wizard"],
  "Oracle" : ["Cipher", "Druid"],
  "Psyblade" : ["Cipher", "Fighter"],
  "Transcendant" : ["Cipher", "Monk"],
  "Inquisitor" : ["Cipher", "Paladin"],
  "Mystic" : ["Cipher", "Priest"],
  "Seer" : ["Cipher", "Ranger"],
  "Mindstalker" : ["Cipher", "Rogue"],
  "Hierophant" : ["Cipher", "Wizard"],
  "Warden" : ["Druid", "Fighter"],
  "Ascetic" : ["Druid", "Monk"],
  "Liberator" : ["Druid", "Paladin"],
  "Universalist" : ["Druid", "Priest"],
  "Beastmaster" : ["Druid", "Ranger"],
  "Pathfinder" : ["Druid", "Rogue"],
  "Sorcerer" : ["Druid", "Wizard"],
  "Brawler" : ["Fighter", "Monk"],
  "Crusader" : ["Fighter", "Paladin"],
  "Cleric" : ["Fighter", "Priest"],
  "Hunter" : ["Fighter", "Ranger"],
  "Swashbuckler" : ["Fighter", "Rogue"],
  "Battlemage" : ["Fighter", "Wizard"],
  "Votary" : ["Monk", "Paladin"],
  "Contemplative" : ["Monk", "Priest"],
  "Wanderer" : ["Monk", "Ranger"],
  "Shadowdancer" : ["Monk", "Rogue"],
  "Sage" : ["Monk", "Wizard"],
  "Templar" : ["Paladin", "Priest"],
  "Shephard" : ["Paladin", "Ranger"],
  "Holy Slayer" : ["Paladin", "Rogue"],
  "Arcane Knight" : ["Paladin", "Wizard"],
  "Itinerant" : ["Priest", "Ranger"],
  "Zealot" : ["Priest", "Rogue"],
  "Thaumaturge" : ["Priest", "Wizard"],
  "Scout" : ["Ranger", "Rogue"],
  "Geomancer" : ["Ranger", "Wizard"],
  "Spellblade" : ["Rogue", "Wizard"],

}

culture_list = ["Aedyr", "The Deadfire Archipelago", "Ixamitl Plains", "Old Vailia", "Rauatai", "The Living Lands", "The White that Wends"]


background_list = ["Drifter", "Hunter", "Labourer", "Merchant"]
